language: node_js
node_js: "8"
matrix:
  include:
    - env: PROJECT=atom NODE_VERSION=6.9.4 DISPLAY=:99.0 CXX=g++-6 CC=gcc-6
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
          - g++-6
          - fakeroot
          - git
          - libsecret-1-dev
          - rpm
          - libx11-dev
          - libxkbfile-dev
    - env: PROJECT=atom-org
    - env: PROJECT=autoprefixer
    - env: PROJECT=chroma.js
    - env: PROJECT=codecombat CXX=g++-4.8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - mongodb-upstart
          packages:
          - mongodb-org-server
          - g++-4.8
        firefox: "52.0"
    - env: PROJECT=coffeelint
    - env: PROJECT=coffeescript
    - env: PROJECT=hubot
    - env: PROJECT=vimium
  # Exclude the default build; we only want to run explicitly-included builds.
  exclude:
    node_js: "8"
before_install:
  - openssl aes-256-cbc -K $encrypted_ca0e70ee0db9_key -iv $encrypted_ca0e70ee0db9_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name 'decaffeinate bot'
  - git config --global user.email 'decaffeinatebot@gmail.com'
  - npm install -g bulk-decaffeinate decaffeinate eslint jscodeshift
  - git clone https://github.com/decaffeinate/decaffeinate-examples.git
script:
  - cd decaffeinate-examples
  - npm install
  - bin/example-runner ${PROJECT} --publish
